### PR TITLE
Allow individual animals to be disabled through settings

### PR DESCRIPTION
**Pull request by AntumDeluge**
Each animal can be disabled with the the option *mobs.enable_\<animal\>*. Setting the value to *false* will cause that animal's script to be skipped from loading.

### CODE REVIEW

**Comment by tenplus1** [comment]
this feature already exists in minetest. conf e. g

mobs_animal:cow = 0 - - disable cow

**Comment by AntumDeluge** [comment]
Is that built-in to Minetest & can be used with any entity?

**Comment by tenplus1** [comment]
This is built into the mobs redo api and allows you to change mob spawn levels and numbers in an area, or by setting to 0 disabling the mob from spawning altogether.

**Comment by AntumDeluge** [comment]
Okay. And that means that the mobs are still registered in-game so they can be referenced or manually spawned.

**Comment by tenplus1** [comment]
exactly

**Pull request closed without merging**
